### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by DaiRongJiang** [crownpku/Information-Extraction-Chinese#108]
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    tf.app.run(main)
  File "C:\Users\2506\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 226, in main
    train()
  File "main.py", line 181, in train
    step, batch_loss = model.run_step(sess, True, batch)
  File "E:\Information-Extraction-Chinese-master\NER_IDCNN_CRF\model.py", line 343, in run_step
    feed_dict)
  File "C:\Users\2506\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\2506\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1089, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "C:\Users\2506\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

請問這樣的問題該如何解決呢?

**Comment by SunYunyun** [comment]
请问你解决了吗，我也遇到这样的问题

**Comment by yassmine-lam** [comment]
Me too. Did u resolve the problem plz?

**Comment by lianliangc** [comment]
请问你解决了吗

**Comment by shenliyan01** [comment]
早都解决了啊，兄弟




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crownpku/Information-Extraction-Chinese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 下午3:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [crownpku/Information-Extraction-Chinese] ValueError: setting an array element with a sequence. (#108)





 
请问你解决了吗

**Comment by CLMPaul** [comment]
你好，可以请问下具体怎么解决的吗
