### ISSUE TITLE
run main.py and have import error

### ISSUE THREAD

**Issue by wangyingshuai** [crownpku/Information-Extraction-Chinese#11]
when I run python3 main.py --train=True --clean=True --model_type=idcnn in my GPU,the error is:
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from model import Model
  File "/root/wangys/NLP/Information-Extraction-Chinese-master/NER_IDCNN_CRF/model.py", line 8, in <module>
    from NER_IDCNN_CRF.utils import result_to_json
ImportError: No module named 'NER_IDCNN_CRF'

**Comment by crownpku** [comment]
model.py, line 8 should be:
```
from utils import result_to_json
```
instead of 
```
from NER_IDCNN_CRF.utils import result_to_json
```

Perhaps something was wrong when you clone the repo?

**Comment by wangyingshuai** [comment]
thank you ,error has solved

**Comment by pythonmwj** [comment]
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    flags.DEFINE_string("result_path",  "result",       "Path for results")
NameError: name 'os' is not defined

我运行怎么会有这个错误？
