### ISSUE TITLE
'ascii' codec error

### ISSUE THREAD

**Issue by wangyingshuai** [crownpku/Information-Extraction-Chinese#12]
when I run python3 main.py --train=True --clean=True --model_type=idcnn in my GPU,the error is:
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from model import Model
  File "/root/wangys/NLP/Information-Extraction-Chinese-master/NER_IDCNN_CRF/model.py", line 8, in <module>
    from NER_IDCNN_CRF.utils import result_to_json
ImportError: No module named 'NER_IDCNN_CRF'

**Comment by wangyingshuai** [comment]
when I run main.py ,the error is :+1: 
Traceback (most recent call last):
  File "main.py", line 228, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 222, in main
    train()
  File "main.py", line 188, in train
    best = evaluate(sess, model, "dev", dev_manager, id_to_tag, logger)
  File "main.py", line 88, in evaluate
    eval_lines = test_ner(ner_results, FLAGS.result_path)
  File "/root/wangys/NLP/Information-Extraction-Chinese-master/NER_IDCNN_CRF/utils.py", line 65, in test_ner
    f.writelines(to_write)
UnicodeEncodeError: 'ascii' codec can't encode character '\uff08' in position 0: ordinal not in range(128)

**Comment by wangyingshuai** [comment]
I solved this problem，when open file ,add encoding="utf8" ,in order to ensure open and write file are all use utf8 encoding.

**Comment by jinxianxian** [comment]
> I solved this problem，when open file ,add encoding="utf8" ,in order to ensure open and write file are all use utf8 encoding.

why not work again
