### ISSUE TITLE
No such file or directory: './data/train_q&a.txt'

### ISSUE THREAD

**Issue by cy163** [crownpku/Information-Extraction-Chinese#58]
Hello,
When I run "python3 initial.py", i got  the following .error message. Pleasehelp.
---------------------
ocentos/Information-Extraction-Chinese-master/RE_BGRU_2ATT$ python3 initial.py
reading word embedding data...
reading relation to id
reading train data...
reading test data ...
organizing train data
Traceback (most recent call last):
  File "initial.py", line 352, in <module>
    init()
  File "initial.py", line 217, in init
    f = open('./data/train_q&a.txt', 'w', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: './data/train_q&a.txt'

**Comment by crownpku** [comment]
Should be file creation permission issue. Please manually create an empty file as ./data/train_q&a.txt and try again.

**Comment by cy163** [comment]
Thank you so much for your reply.

Furthermore, I notice that there are two files train.txt and test.txt in the fold of origin_data. Undoutly, 'train.txt' is created  for building  the model, but i cannot understand why  'test.txt' file is needed ? What's the role does it play in executing initial.py .
________________________________
发件人: Guan Wang <notifications@github.com>
发送时间: 2018年5月14日 10:57
收件人: crownpku/Information-Extraction-Chinese
抄送: cy163; Author
主题: Re: [crownpku/Information-Extraction-Chinese] No such file or directory: './data/train_q&a.txt' (#58)


Should be file creation permission issue. Please manually create an empty file as ./data/train_q&a.txt and try again.

―

**Comment by crownpku** [comment]
test.txt is for evaluation of the model to get accuracy. If you are only running the command line testing process then this file is not important.

**Comment by cy163** [comment]
Thank you for your reply.
Please show me how to prepare a good 'test.txt' file for  executing initial.py to get a better model. I notice that the rows of text in 'test.txt is less than that in 'train.txt''. Can I simply selecting some rows of text into 'test.txt'0 from 'train.txt'. Or, i have to do this according to some rules.
Thanks.
