### ISSUE TITLE
tensorflow 1.10 运行报错 02

### ISSUE THREAD

**Issue by huwen2117** [crownpku/Information-Extraction-Chinese#81]
Traceback (most recent call last):
  File "D:\python\python install\helpers\pydev\pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\python\python install\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF/main.py", line 228, in <module>
    tf.app.run(main)
  File "G:\pythonDevelop\venv1\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF/main.py", line 222, in main
    train()
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF/main.py", line 188, in train
    best = evaluate(sess, model, "dev", dev_manager, id_to_tag, logger)
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF/main.py", line 88, in evaluate
    eval_lines = test_ner(ner_results, FLAGS.result_path)
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF\utils.py", line 66, in test_ner
    eval_lines = return_report(output_file)
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF\conlleval.py", line 282, in return_report
    counts = evaluate(f)
  File "G:/pythonDevelop/Extraction/NER_IDCNN_CRF\conlleval.py", line 74, in evaluate
    for line in iterable:
  File "G:\pythonDevelop\venv1\lib\codecs.py", line 713, in __next__
    return next(self.reader)
  File "G:\pythonDevelop\venv1\lib\codecs.py", line 644, in __next__
    line = self.readline()
  File "G:\pythonDevelop\venv1\lib\codecs.py", line 557, in readline
    data = self.read(readsize, firstline=True)
  File "G:\pythonDevelop\venv1\lib\codecs.py", line 503, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 0: invalid start byte

**Comment by huwen2117** [comment]
I change line 58 to :
with open(output_file, "w", encoding='utf8') as f:

def test_ner(results, path):
    """
    Run perl script to evaluate model
    """
    output_file = os.path.join(path, "ner_predict.utf8")
    with open(output_file, "w") as f: # line 58
        to_write = []
        for block in results:
            for line in block:
                to_write.append(line + "\n")
            to_write.append("\n")

        f.writelines(to_write)
    eval_lines = return_report(output_file)
    return eval_lines
