### ISSUE TITLE
python3.6 python main.py --ckpt_path=ckpt_IDCNN

### ISSUE THREAD

**Issue by weilongheal** [crownpku/Information-Extraction-Chinese#86]
在进行NER的测试时,在控制台输入值后,没有输出,怎么解决呢?但是读取test.txt的方法测试是有输出的;
还有就是input在3.5的时候有BUG,最好使用3.6;

**Comment by forconz** [comment]
我用的3.6，正常运行的

你这边进行NER测试，是测试什么？最好截图说一下

**Comment by forconz** [comment]
python main.py --ckpt_path=ckpt_IDCNN
请输入测试句子:近日，腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议。
{'string': '近日,腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议。', 'entities': [{'word': '特斯拉', 'start': 14, 'end': 17, 'type': 'LOC'}]}

特斯拉应该是ORG，不是LOC。
腾讯没有被识别出来。

我现在只知道怎么用，不知道如何改善这个库。
这个库效率很高。

我这边能采集，并做实体标注，可以生成类似{'string': '近日,腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议。', 'entities': [{'word': '特斯拉', 'start': 14, 'end': 17, 'type': 'LOC'}]}这样的语料，但是实体标注后的语料，如何变成这个库用的训练文本，就不知道怎么做了。

**Comment by weilongheal** [comment]
是RE关系抽取的时候测试有问题,就像作者说的一个BUG,


请输入中文句子，格式为 "name1 name2 sentence":张三 李四 张三喜欢李四.
Traceback (most recent call last):
  File "test_GRU.py", line 348, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "test_GRU.py", line 226, in main
    print(line)
  File "/usr/lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-5: surrogates not allowed

**Comment by weilongheal** [comment]
不用input的话,可以正常输出:
{'string': '香港的房价已经到达历史巅峰,乌溪沙地铁站上盖由新鸿基地产公司开发的银湖天峰,现在的尺价已经超过一万五千港币。', 'entities': [{'word': '香港', 'start': 0, 'end': 2, 'type': 'LOC'}, {'word': '乌溪沙地铁站', 'start': 14, 'end': 20, 'type': 'LOC'}, {'word': '新鸿基地产公司', 'start': 23, 'end': 30, 'type': 'ORG'}, {'word': '银湖', 'start': 33, 'end': 35, 'type': 'LOC'}]}

感觉python3的input很多坑,

**Comment by forconz** [comment]
@weilongheal 我在windows下显示正常，你可能在linux下
你解码就正常显示了，

\u开头表示的是Unicode编码
解决办法:
print(path.decode("raw_unicode_escape"))
![1529917422_969892](https://user-images.githubusercontent.com/9990289/45688400-d98ff400-bb83-11e8-9503-c04deac246f8.png)

编码的维妮塔，应该是这么解

**Comment by forconz** [comment]
@crownpku 你用什么工具标注？手工标注搞死人的

**Comment by forconz** [comment]
@crownpku 

> 参考data文件夹中训练数据的格式，把你采集和标注好的数据放进去，重新训练模型就好了。

帮忙看看我的思路对不对：

腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议
需要识别出机构：腾讯，特斯拉
特斯拉不能显示为LOC

1、用这个工具 https://github.com/jiesutd/YEDDA 做标注，比如对特斯拉，对腾讯进行ORG标注。

2、YEDDA工具导出类似 https://github.com/shiyybua/NER/blob/master/resource/target.txt 这种格式，这种格式是BIO标注方式？**帮在线打开确认下标注方式。**

3、然后再用这个代码:
[Convert BIO to BIOES](https://github.com/daniyuu/bio2bioes)
转换成BIOES标注方式.

3、训练 train with IDCNN+CRF (default)
#python3 main.py --train=True --clean=True --model_type=idcnn

4、python main.py --ckpt_path=ckpt_IDCNN
再次输入：腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议
看看实体识别结果。

您看这个思路对吗？

**Comment by weilongheal** [comment]
@forconz 你好我用的是linux,昨天验证过我的编码格式是UTF-8,尝试解码再编码成UTF-8,但是未成功,

你说的那个是str.decode()成固定编码是吗.但是python3没有这个方法,
你们的标记工具我得好好看看,

**Comment by weilongheal** [comment]
@forconz @crownpku 你好,请问下我们这个基于字符级别的NER,字向量是如何生成的呢?词向量可以用Word2vector,glove,

**Comment by forconz** [comment]
@weilongheal 😰，我也在发愁这个问题，搞不定，我就没继续往下搞了。

我现在做中文标注，做语料，都不知道怎么搞

**Comment by weilongheal** [comment]
@forconz 你好,我是这么想的,基于字符级别的向量的生成和基于词的向量如Word2vec是一样,我们的输入数据由句子的词改为单个字符,训练过程还是一样的;
你是手工标注语料吗?

**Comment by crownpku** [comment]
> @forconz @crownpku 你好,请问下我们这个基于字符级别的NER,字向量是如何生成的呢?词向量可以用Word2vector,glove,

data下面有提前训练好的中文字向量。如果要自己训练，只要把单位由词改为单个中文字就好了。

**Comment by forconz** [comment]
@weilongheal 是啊，我知道怎么用这个开源代码， 但是不知道怎么改进，开源代码都识别不了天猫这个机构，发愁...我这边擅长开发采集系统和信息管理系统，我用这个开源代码抽取机构等信息。说实话，这个代码非常棒，效率非常高，我就是想改进下，不知道怎么入手...

**Comment by forconz** [comment]
@crownpku 就是想自己训练，不知道怎么入手，就算买本书都不知道买什么书... 关于文本训练的关键词都搜过了，对具体怎么做训练，都说的很简略。

如果是按data下面的结构准备语料，理论上是可以的，但实际上用的中文标注结果，实际上跟本开源代码跑出来的结构有些类似，就是标记哪些字符串是机构，哪些字符串是人名，但是这个json格式的标注，如何转换成data下面的训练结果，就不知道怎么搞了。

另外一种思路，就是用这个工具 https://github.com/jiesutd/YEDDA 做标注，貌似BIO标注方式（但是我不确定），然后用代码调用转换成BIOES标注方式，不知道这个思路对不对，没人帮解答，苦恼中...


帮忙看看我的思路对不对：

腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议
需要识别出机构：腾讯，特斯拉
特斯拉不能显示为LOC

1、用这个工具 https://github.com/jiesutd/YEDDA 做标注，比如对特斯拉，对腾讯进行ORG标注。

2、YEDDA工具导出类似 https://github.com/shiyybua/NER/blob/master/resource/target.txt 这种格式，这种格式是BIO标注方式？帮在线打开确认下标注方式。

3、然后再用这个代码:
Convert BIO to BIOES
转换成BIOES标注方式.

3、训练 train with IDCNN+CRF (default)
#python3 main.py --train=True --clean=True --model_type=idcnn

4、python main.py --ckpt_path=ckpt_IDCNN
再次输入：腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议
看看实体识别结果。

您看这个思路对吗？

**Comment by forconz** [comment]
@crownpku  ？？？

**Comment by Feny321** [comment]
> @crownpku 就是想自己训练，不知道怎么入手，就算买本书都不知道买什么书... 关于文本训练的关键词都搜过了，对具体怎么做训练，都说的很简略。
> 
> 如果是按data下面的结构准备语料，理论上是可以的，但实际上用的中文标注结果，实际上跟本开源代码跑出来的结构有些类似，就是标记哪些字符串是机构，哪些字符串是人名，但是这个json格式的标注，如何转换成data下面的训练结果，就不知道怎么搞了。
> 
> 另外一种思路，就是用这个工具 https://github.com/jiesutd/YEDDA 做标注，貌似BIO标注方式（但是我不确定），然后用代码调用转换成BIOES标注方式，不知道这个思路对不对，没人帮解答，苦恼中...
> 
> 帮忙看看我的思路对不对：
> 
> 腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议
> 需要识别出机构：腾讯，特斯拉
> 特斯拉不能显示为LOC
> 
> 1、用这个工具 https://github.com/jiesutd/YEDDA 做标注，比如对特斯拉，对腾讯进行ORG标注。
> 
> 2、YEDDA工具导出类似 https://github.com/shiyybua/NER/blob/master/resource/target.txt 这种格式，这种格式是BIO标注方式？帮在线打开确认下标注方式。
> 
> 3、然后再用这个代码:
> Convert BIO to BIOES
> 转换成BIOES标注方式.
> 
> 3、训练 train with IDCNN+CRF (default)
> #python3 main.py --train=True --clean=True --model_type=idcnn
> 
> 4、python main.py --ckpt_path=ckpt_IDCNN
> 再次输入：腾讯以近18亿美元入股特斯拉成第五大股东的消息引发了外界大量猜测和热议
> 看看实体识别结果。
> 
> 您看这个思路对吗？

这个方法可以实现么，我现在想训练自己的数据，怎么整呢？
